export enum KitchenCabinetType {
  BASE_ONE_DOOR = 'BASE_ONE_DOOR',
  BASE_TWO_DOOR = 'BASE_TWO_DOOR',
  BASE_WITH_DRAWERS = 'BASE_WITH_DRAWERS',
  TALL_CABINET = 'TALL_CABINET',
  CORNER_CABINET = 'CORNER_CABINET',
  UPPER_ONE_DOOR = 'UPPER_ONE_DOOR',
  UPPER_TWO_DOOR = 'UPPER_TWO_DOOR',
  UPPER_OPEN_SHELF = 'UPPER_OPEN_SHELF',
  UPPER_CASCADE = 'UPPER_CASCADE'
}
